# Generated by Django 6.0.3 on 2026-09-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CareerGoal',
        ),
    ]
